// demo-vue/src/App.vue
<template>
    <nav>
        <router-link to="/view1">HomePage</router-link>
        <router-link to="/view1">Scenario1</router-link>
        <router-link to="/view2">Scenario2</router-link>
<!--        <router-link to="/view3">Scenario3</router-link>-->
    </nav>
    <router-view></router-view>
</template>

<script>
export default {
  name: 'App',
  components: {
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// demo-react/src/App.js
//import logo from './logo.svg';
import './App.css';

import React from 'react';
import { BrowserRouter as Router, Link, Routes, Route } from 'react-router-dom';
import HomePage from './components/HomePage';
import FirstView from './components/FirstView';
import SecondView from './components/SecondView';
import ThirdView from './components/ThirdView';

const App = () => {
  return (
    <Router>
      <div>
        <nav>
          <Link to="/homepage">HomePage</Link>
          <Link to="/view1">Scenario1</Link>
          <Link to="/view2">Scenario2</Link>
          <Link to="/view3">Scenario3</Link>
        </nav>
        <Routes>
          <Route path="/" element={<h1>Welcome to HomePage</h1>} />
          <Route path="/homepage" element={<HomePage />} />
          <Route path="/view1" element={<FirstView />} />
          <Route path="/view2" element={<SecondView />} />
          <Route path="/view3" element={<ThirdView />} />
        </Routes>
      </div>
    </Router>
  );
};

export default App;
