// demo-vue/src/components/FirstView.vue
<template>
    <div>
        <button @click="getData1">Get Data</button>
        <h1>This is 1st View</h1>
        <ul>
            <li v-for="(item, index) in data" :key="index">{{ item }}</li>
        </ul>
        <button @click="getData2">Get Data</button>
    </div>
</template>

<script>
import axios from 'axios';

export default {
    name: 'FirstView',
    props: {
        msg: String
    },
    data() {
        return {
            data: [],
        };
    },
    methods: {
        async getData1() {
            try {
                const response = await axios.get('http://127.0.0.1:5000/sentiments');
                console.log(response.data);
                this.data = response.data;
            } catch (error) {
                console.log(error);
            }
        },
        async getData2() {
            try {
                const response = await axios.post('http://127.0.0.1:5000/sentiments');
                console.log(response.data);
                this.data = response.data;
            } catch (error) {
                console.log(error);
            }
        },
    },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
    margin: 40px 0 0;
}
ul {
    list-style-type: none;
    padding: 0;
}
li {
    display: inline-block;
    margin: 0 10px;
}
a {
    color: #42b983;
}
</style>

// demo-react/src/components/FirstView.js
import React, { useState } from 'react';
import axios from 'axios';

const FirstView = ({msg}) => {
  const [data, setData] = useState([]);

  const getData1 = async () => {
    try {
      const response = await axios.get('http://127.0.0.1:5000/sentiments');
      console.log(response.data);
      setData(response.data);
    } catch (error) {
      console.log(error);
    }
  };

  const getData2 = async () => {
    try {
      const response = await axios.post('http://127.0.0.1:5000/sentiments');
      console.log(response.data);
      setData(response.data);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div>
      <button onClick={getData1}>Get Data</button>
      <h1>This is 1st View</h1>
      <ul>
        {data.map((item, index) => (
          <li key={index}>{item}</li>
        ))}
      </ul>
      <button onClick={getData2}>Get Data</button>
    </div>
  );
};

export default FirstView;
